[workspace]
members = ["./crates/*"]
default-members = ["./crates/tlb"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tlb.path = "./crates/tlb"
tlbits.path = "./crates/bits"
tlb-ton.path = "./crates/ton"

base64 = "0.21"
bitvec = "1"
either = "1"
hex = "0.4"
impl-tools = "0.10"
itertools = "0.12"
num-bigint = "0.4"
sha2 = "0.10"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"

tonlib = "0.12"
