[package]
name = "tlb"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1"
either = "1"
hex = "0.4"
impl-tools = "0.10"
itertools = "0.12"
num-bigint = "0.4"
sha2 = "0.10"
thiserror = "1"

[dev-dependencies]
hex-literal = "0.4"
