[package]
name = "tlb-ton"
version = "0.2.10"
edition.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Common TL-B types for TON blockchain"

[dependencies]
tlb.workspace = true
tlbits.workspace = true

base64.workspace = true
bitvec.workspace = true
chrono.workspace = true
crc = "3"
either.workspace = true
impl-tools.workspace = true
hex.workspace = true
num-bigint.workspace = true
serde_with = { workspace = true, optional = true }
strum.workspace = true

[dev-dependencies]
serde_json = "1"

[features]
serde = ["dep:serde_with"]
